[project]
name = "airflow-docker-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "psycopg2>=2.9.11",
]
